"""Calibrate the trained classifier — MVP_PLAN.md step 2.3.

    python ml/calibrate.py

Runs the fine-tuned model over the `calib` split, fits Platt scaling, and writes
`artifacts/calibrator.json` plus a reliability report.

Gate: ECE <= 0.05 after calibration, and strictly better than before.

## Why `calib` and not `val`

`val` selected the checkpoint. Fitting calibration on the same split produces
probabilities that look calibrated there and are overconfident on anything else —
the model was chosen partly *because* of how it scored those examples. That is why
`ml/prepare_data.py` carves out a fourth split used for nothing else.

Without this step, the Integrity Score is an arbitrary monotone transform of an
arbitrary number, and the concept paper's claim (section 3.3) that the score is a
calibrated confidence has nothing behind it.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
import torch  # noqa: E402
from torch.utils.data import DataLoader  # noqa: E402

from ml.calibration import (  # noqa: E402
    PlattCalibrator,
    expected_calibration_error,
    reliability_table,
)
from ml.feature_contract import LABEL_COLUMN  # noqa: E402
from ml.metrics import evaluate  # noqa: E402
from ml.train_transformer import encode, load_split  # noqa: E402

ECE_GATE = 0.05


@torch.no_grad()
def score_split(model, loader, device) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return (labels, uncalibrated p_fraud, logit margin)."""
    model.eval()
    labels, probabilities, margins = [], [], []
    for ids, mask, y in loader:
        logits = model(input_ids=ids.to(device), attention_mask=mask.to(device)).logits.float()
        probabilities.append(torch.softmax(logits, dim=-1)[:, 1].cpu().numpy())
        # Margin = logit_fraud - logit_real. This is the quantity Platt scaling
        # rescales; using the probability directly would apply a sigmoid twice.
        margins.append((logits[:, 1] - logits[:, 0]).cpu().numpy())
        labels.append(y.numpy())
    return (
        np.concatenate(labels),
        np.concatenate(probabilities),
        np.concatenate(margins),
    )


def render_report(before, after, metrics_before, metrics_after, calibrator, n: int) -> str:
    passed = after.ece <= ECE_GATE and after.ece < before.ece
    lines = [
        "# Calibration report",
        "",
        "Generated by `ml/calibrate.py`. Platt scaling fitted on the `calib` split",
        f"({n} rows), which the model never trained on and was never selected against.",
        "",
        "## Gate 2.3",
        "",
        f"Target ECE <= {ECE_GATE}, and better than before calibration.",
        f"Result: **{after.ece:.4f}** (was {before.ece:.4f}) — "
        f"**{'PASS' if passed else 'FAIL'}**.",
        "",
        "## Metrics",
        "",
        "| metric | before | after | change |",
        "| --- | ---: | ---: | ---: |",
        f"| ECE | {before.ece:.4f} | {after.ece:.4f} | {after.ece - before.ece:+.4f} |",
        f"| Brier | {before.brier:.4f} | {after.brier:.4f} | {after.brier - before.brier:+.4f} |",
        f"| max bin error | {before.max_calibration_error:.4f} | "
        f"{after.max_calibration_error:.4f} | "
        f"{after.max_calibration_error - before.max_calibration_error:+.4f} |",
        f"| PR-AUC | {metrics_before.pr_auc:.4f} | {metrics_after.pr_auc:.4f} | "
        f"{metrics_after.pr_auc - metrics_before.pr_auc:+.4f} |",
        "",
        "PR-AUC must be unchanged: Platt scaling is monotone, so it cannot alter",
        "ranking. A change here means something other than calibration happened.",
        "",
        f"Fitted parameters: `a = {calibrator.a:.4f}`, `b = {calibrator.b:.4f}`",
        "",
        "## Reliability, before calibration",
        "",
        reliability_table(before),
        "",
        "## Reliability, after calibration",
        "",
        reliability_table(after),
        "",
        "Each row asks: of the predictions in this confidence band, what fraction",
        "were actually fraudulent? A calibrated model has `mean predicted` close to",
        "`observed` in every populated bin.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-dir", type=Path, default=Path("artifacts/scam_model"))
    parser.add_argument("--processed", type=Path, default=Path("data/processed"))
    parser.add_argument("--out", type=Path, default=Path("artifacts/calibrator.json"))
    parser.add_argument("--report", type=Path, default=Path("eval/calibration_report.md"))
    parser.add_argument("--max-length", type=int, default=256)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--bins", type=int, default=10)
    parser.add_argument("--threads", type=int, default=0)
    args = parser.parse_args()

    if not (args.model_dir / "config.json").exists():
        raise SystemExit(
            f"No trained model at {args.model_dir}. Run: python ml/train_transformer.py"
        )

    torch.set_num_threads(args.threads or os.cpu_count() or 4)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    from transformers import AutoModelForSequenceClassification, AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(args.model_dir)
    model = AutoModelForSequenceClassification.from_pretrained(args.model_dir).to(device)

    calib_df: pd.DataFrame = load_split(args.processed, "calib")
    dataset = encode(
        tokenizer,
        calib_df,
        args.max_length,
        args.processed / "token_cache" / f"calib_{args.max_length}.pt",
    )
    loader = DataLoader(dataset, batch_size=args.batch_size)

    print(f"scoring {len(calib_df)} calibration rows on {device} ...")
    labels, raw_probabilities, margins = score_split(model, loader, device)

    calibrator = PlattCalibrator().fit(margins, labels)
    calibrated = calibrator.transform(margins)

    before = expected_calibration_error(labels, raw_probabilities, args.bins)
    after = expected_calibration_error(labels, calibrated, args.bins)
    metrics_before = evaluate("uncalibrated", labels, raw_probabilities)
    metrics_after = evaluate("calibrated", labels, calibrated)

    print(f"\n  ECE   {before.ece:.4f} -> {after.ece:.4f}")
    print(f"  Brier {before.brier:.4f} -> {after.brier:.4f}")
    print(f"  PR-AUC {metrics_before.pr_auc:.4f} -> {metrics_after.pr_auc:.4f} (must not change)")
    print(f"  a = {calibrator.a:.4f}, b = {calibrator.b:.4f}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        json.dumps(
            {
                **calibrator.to_dict(),
                "fitted_on": "calib",
                "n_rows": len(calib_df),
                "max_length": args.max_length,
                "ece_before": before.ece,
                "ece_after": after.ece,
                "brier_before": before.brier,
                "brier_after": after.brier,
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(
        render_report(before, after, metrics_before, metrics_after, calibrator, len(calib_df)),
        encoding="utf-8",
    )

    passed = after.ece <= ECE_GATE and after.ece < before.ece
    print(f"\nwrote {args.out}")
    print(f"wrote {args.report}")
    print(f"Gate 2.3 (ECE <= {ECE_GATE} and improved): {'PASS' if passed else 'FAIL'}")
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
